# Generated by Django 4.0.5 on 2023-09-14 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits without spaces or dashes and must be exactly 11 digits', regex='^\\d{11}$')])),
                ('hostel', models.CharField(max_length=250)),
                ('location', models.CharField(choices=[('Location1', 'L1'), ('Location2', 'L2'), ('Null', 'Null')], default='Null', max_length=9, null=True)),
                ('comment', models.CharField(max_length=400)),
            ],
        ),
    ]
